spring:
  application:
    name: seat-reservation
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/seats
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

server:
  tomcat:
    accept-count: 1000        #this is waiting queue(default 100)
    max-connections: 10000
    threads:
      max: 200