spring:
  application:
    name: seat-reservation
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/seats}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-components: always
      group:
        readiness:
          include:
            - readinessState
            - db
        liveness:
          include:
            - livenessState

server:
  port: ${PORT:8080}
  tomcat:
    accept-count: 1000        #this is waiting queue(default 100)
    max-connections: 10000
    threads:
      max: 200